name: terraform-lint
description: https://github.com/champtitles/action-terraform-lint
runs:
  using: "composite"
  steps:
    - name: terraform fmt
      shell: bash
      run: terraform fmt -recursive -check

    - name: tflint
      shell: bash
      run: |
        cp ${GITHUB_ACTION_PATH}/.tflint.hcl .
        tflint --init
        tflint