name: terraform-lint
description: https://github.com/champtitles/action-terraform-lint
runs:
  using: "composite"
  steps:
    - name: terraform fmt
      shell: bash
      run: terraform fmt -recursive -check

    - name: tflint
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        cp ${GITHUB_ACTION_PATH}/.tflint.hcl .
        tflint --init
        for dir in `find . -type d -not -path "./.git/*"`; do tflint $dir; done