name: terraform-lint
description: https://github.com/champtitles/action-terraform-lint
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -LO https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep_13.0.0_amd64.deb
        sudo dpkg -i ripgrep_13.0.0_amd64.deb

        # run all check scripts
        cp ${GITHUB_ACTION_PATH}/*.sh .
        ls -la
        find . -name "check_*.sh" | xargs -t -I{} bash {} .