name: terraform-lint
description: https://github.com/champtitles/action-terraform-lint
runs:
  using: "composite"
  steps:
    - name: terraform fmt
      shell: bash
      run: terraform fmt -recursive -check

    - name: tflint
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        cp ${GITHUB_ACTION_PATH}/.tflint.hcl .
        tflint --init

        TF_DIRS=$(find . -name "*.tf" -not -path "./.git/*" -exec dirname {} \; | sort | uniq)
        set +e
        for dir in $TF_DIRS; do echo $dir; tflint $dir; done